### ISSUE TITLE
Survey Queue Table

### ISSUE THREAD

**Issue by jhscoordinatingcenter** [ctsit/redcap_css_injector#13]
This is not a issue but a feature request:
Could you add a feature to change the color of the Instrument Name, Arrange the instruments into Blocks or sections?
![InstrumentColor](https://user-images.githubusercontent.com/41167346/189356341-78f00d58-2a0e-4fda-8533-989afeb99a6d.JPG)
![InstrumentNameColor](https://user-images.githubusercontent.com/41167346/189356354-2689754b-9d60-4e9b-9c17-2b7dd8863d3b.JPG)
Thank you

**Comment by pbchase** [comment]
@jhscoordinatingcenter, that's not the scope of this module. We don't write the CSS, we just deliver it to the page. Sorry, but I'm going to close this issue.
