### ISSUE TITLE
Do not call functions from ExternalModules directly

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/redcap_css_injector#7]
See [official documentation](https://github.com/vanderbilt/redcap-external-modules/blob/testing/docs/official-documentation.md#available-developer-methods-in-external-modules) and [issue](https://github.com/vanderbilt/redcap-external-modules/issues/246#issuecomment-579413815).

Recommend something like `sed s/ExternalModules::/$this->/g` to correct but each line will need to be inspected.

**Comment by jrpence** [comment]
look like it was already addressed.. https://github.com/ctsit/redcap_css_injector/commit/d18c4d0caf1b796f440416ba1812d2afa8ca678b
there was just one use statement left over though...

**Comment by ChemiKyle** [comment]
Indeed, I don't see any meaningful results with `grep -r . -e '::'` so I'll close this issue.  
Sorry for the non-existent goose chase!
